-- DROP & CREATE SEQUENCE, TABLE
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
    cID VARCHAR2(50) PRIMARY KEY,
    cPW VARCHAR2(50) NOT NULL,
    cNAME VARCHAR2(50) NOT NULL,
    cTEL VARCHAR2(50),
    cEMAIL VARCHAR2(50),
    cADDRESS VARCHAR2(50),
    cBIRTH DATE,
    cGENDER VARCHAR2(1),
    cRDATE DATE DEFAULT SYSDATE NOT NULL
);
