DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_NO_SEQ;
CREATE SEQUENCE FRIEND_NO_SEQ
    MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE TABLE FRIEND(
    NO NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(50)
);    
SELECT * FROM FRIEND;

INSERT INTO FRIEND VALUES(FRIEND_NO_SEQ.NEXTVAL, '마이콜', '010-5252-522');
INSERT INTO FRIEND (NO, NAME, TEL)
        VALUES(FRIEND_NO_SEQ.NEXTVAL, '또치', '010-5757-1111');
        
SELECT * FROM FRIEND ORDER BY NO;
SELECT * FROM FRIEND WHERE NAME LIKE '%'||'치'||'%';
SELECT * FROM FRIEND WHERE NAME LIKE '%'||'둘'||'%' AND TEL LIKE '%'||'5252'||'%';

COMMIT;