 -- 프로그램 쿼리
 -- 1. 
 INSERT INTO PERSON 
    VALUES (PERSON_PNO_SQ.NEXTVAL, '홍길동', (SELECT JNO FROM JOB WHERE JNAME='배우'), 99, 99, 100);
SELECT * FROM PERSON;
COMMIT;


--2.
SELECT PNAME||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
    FROM PERSON P, JOB J
    WHERE P.JNO=J.JNO;
    