-- table및 sequence 제거
DROP TABLE MVC_BOARD;
DROP SEQUENCE MVC_BOARD_SEQ;
-- table및 sequence 생성
CREATE SEQUENCE MVC_BOARD_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;

CREATE TABLE MVC_BOARD(
    bID      NUMBER(6) PRIMARY KEY,  -- 글번호
    bNAME    VARCHAR2(50) NOT NULL,  -- 글쓴이
    bTITLE   VARCHAR2(100) NOT NULL, -- 글제목
    bCONTENT VARCHAR2(1000),         -- 글본문
    bDATE    DATE DEFAULT SYSDATE NOT NULL, -- 글 작성시점
    bHIT     NUMBER(6) DEFAULT 0 NOT NULL, -- 글 조회수 
    bGROUP   NUMBER(6) NOT NULL, -- 글그룹
    bSTEP    NUMBER(3) NOT NULL, -- 글그룹내 출력 순서(원글 0)
    bINDENT  NUMBER(3) NOT NULL, -- 글 LIST 출력시 글 제목 들여쓰기 정도 (원글0)
    BIP      VARCHAR2(50) NOT NULL -- 글 쓴 컴퓨터의 IP
);
-- dummy data (3개 이상 - 2개원글 + 1개 답변글)
INSERT INTO MVC_BOARD (bID, bNAME, bTITLE, bCONTENT, bGROUP, bSTEP, bINDENT, bIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'HONH', 'TITLE', 'CONTENT', MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.0.0.5');
INSERT INTO MVC_BOARD (bID, bNAME, bTITLE, bCONTENT, bGROUP, bSTEP, bINDENT, bIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'SHIN', 'TITLE2', 'CONTENT2', MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.0.0.9'); 
INSERT INTO MVC_BOARD (bID, bNAME, bTITLE, bCONTENT, bGROUP, bSTEP, bINDENT, bIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'JEONG', 'TITLE3', 'CONTENT3', MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.0.0.8'); 
-- dao에 들어갈 query
-- 1. 글목록 (startRow부터 endRow)
SELECT *
    FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP) A)
    WHERE RN BETWEEN 2 AND 3;
    
-- 2. 글갯수
SELECT COUNT(*) CNT  FROM MVC_BOARD;

-- 3. 원글쓰기 (사용자로부터 입력받은 bname, btitle, bcontent, bip, bgroup은 글번호, bstep, bindent은 0)
INSERT INTO MVC_BOARD (bID, bNAME, bTITLE, bCONTENT, bGROUP, bSTEP, bINDENT, bIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'DUL', 'TITLE4', 'CONTENT', MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.0.0.5');
    
-- 4. bid로 조회수 1 올리기
UPDATE MVC_BOARD SET BHIT = BHIT+1 WHERE BID=1;
SELECT * FROM MVC_BOARD;

-- 5. bid로 dto가져오기
SELECT * FROM MVC_BOARD WHERE BID=1;
-- 6. 글수정 (특정 bid의 bname, btitle, bcontent, bip 수정)
UPDATE MVC_BOARD
    SET BNAME = 'JENOG',
        BTITLE = '제목',
        BCONTENT = '컨텐츠',
        BIP = '198.0.11.192'
    WHERE BID = 1;
-- 7. 글삭제 (특정 bid 삭제)
DELETE FROM MVC_BOARD WHERE BID = 2;
ROLLBACK;
-- 8. 답변글 저장 전단계(엑셀 ⓐ 단계)
UPDATE MVC_BOARD SET BSTEP = BSTEP+1
    WHERE BGROUP =1 AND BSTEP>0;
-- 9. 답변글 저장
INSERT INTO MVC_BOARD (bID, bNAME, bTITLE, bCONTENT, bGROUP, bSTEP, bINDENT, bIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'JEONG', '제목2', '둘리', MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.0.0.1');
COMMIT;